arqon:
  search:
    enabled: true
    mongo:
      enabled: false
    elasticsearch:
      enabled: true


playground:
  mongo:
    uri: mongodb://localhost:27017
    database: arqon-search
  elasticsearch:
    host: localhost
    port: 9200
    scheme: http